title: Marilene's Blog
author: Marilene Andrade Garcia
email: marilene.agarcia@gmail.com
description: >-
  Welcome to my GitHub Pages Blog site.

theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
